require('dotenv').config();
const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
    }
});

const alertCooldowns = new Map();
const COOLDOWN_TIME = 60 * 1000;

/**
 * Sends a formal security notification.
 */
const sendVlmAlert = async (data, isThreat) => {
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) return;

    const nodeId = data.node_id || "SYSTEM_NODE";
    const now = Date.now();

    // Prevent inbox flooding
    if (alertCooldowns.has(nodeId)) {
        if (now - alertCooldowns.get(nodeId) < COOLDOWN_TIME) return;
    }
    alertCooldowns.set(nodeId, now);

    // --- FORMAL MESSAGE CONFIGURATION ---
    const config = isThreat ? {
        subject: `URGENT: Security Breach Notification - Node ${nodeId}`,
        header: "SECURITY BREACH DETECTED",
        color: "#b91c1c", // Dark Red
        detailLabel: "Incident Description",
        status: "IMMEDIATE ATTENTION REQUIRED"
    } : {
        subject: `Status Update: Security Check Clear - Node ${nodeId}`,
        header: "OPERATIONAL STATUS: SECURE",
        color: "#15803d", // Dark Green
        detailLabel: "Verification Details",
        status: "NO ACTION REQUIRED"
    };

    const mailOptions = {
        from: `"RailGuard Security" <${process.env.EMAIL_USER}>`,
        to: process.env.ALERT_RECEIVER,
        subject: config.subject,
        html: `
            <div style="font-family: Arial, sans-serif; color: #334155; max-width: 600px; border: 1px solid #e2e8f0; margin: auto;">
                <div style="background-color: ${config.color}; color: white; padding: 15px; font-weight: bold; font-size: 18px;">
                    ${config.header}
                </div>
                <div style="padding: 20px; line-height: 1.6;">
                    <p>This automated notification is to inform you of a security assessment conducted at <strong>Node ${nodeId}</strong>.</p>
                    
                    <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                        <tr>
                            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; width: 40%;">Current Status:</td>
                            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; font-weight: bold; color: ${config.color};">${config.status}</td>
                        </tr>
                        <tr>
                            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b;">Timestamp:</td>
                            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9;">${new Date().toLocaleString()}</td>
                        </tr>
                        <tr>
                            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b;">${config.detailLabel}:</td>
                            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9;">${data.reason || "Monitoring check complete."}</td>
                        </tr>
                    </table>

                    <p style="font-size: 12px; color: #94a3b8; margin-top: 30px; border-top: 1px solid #f1f5f9; padding-top: 15px;">
                        <strong>System Note:</strong> This is a formal report generated by the RailGuard Visual Monitoring System. 
                        For live telemetry and full diagnostic logs, please access the <a href="http://localhost:5173" style="color: ${config.color}; text-decoration: none; font-weight: bold;">Security Command Center</a>.
                    </p>
                </div>
            </div>
        `
    };

    try {
        await transporter.sendMail(mailOptions);
        console.log(`[Email-Service] Formal ${isThreat ? 'Alert' : 'Status Update'} sent for Node ${nodeId}`);
    } catch (error) {
        console.error('[Email-Service] Failed to send notification:', error.message);
    }
};

module.exports = { sendVlmAlert }; // Export the new function name